#!/usr/bin/env python3
# REST API for the PricerBot database.
#
# Usage:
#   python api.py            – start on http://localhost:8000
#   python api.py --port 9000
#
# Endpoints:
#   GET /price?model=iPhone+14+Pro          – latest summary for one model
#   GET /prices?brand=Apple                 – latest summary for all models (optional brand filter)
#   GET /health                             – liveness check
#
# Interactive docs (auto-generated by FastAPI):
#   http://localhost:8000/docs

import argparse
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import JSONResponse

from database.alchemy.database import init_db, get_latest_summary, get_avg_price_for_model

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

@asynccontextmanager
async def lifespan(_app: FastAPI):
    init_db()
    yield

app = FastAPI(title="PricerBot API", version="1.0.0", lifespan=lifespan)


# ─────────────────────────────────────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.get("/price")
def get_price(model: str = Query(..., description="Phone model name, e.g. 'iPhone 14 Pro'")) -> dict:
    # Returns the latest price summary for a single model.
    results = get_latest_summary(model=model)
    if not results:
        raise HTTPException(status_code=404, detail=f"No price data found for '{model}'")
    # get_latest_summary does a LIKE match — return the closest (first) hit
    return results[0]


@app.get("/prices")
def get_prices(brand: str | None = Query(None, description="Filter by brand, e.g. 'Apple'")) -> list:
    # Returns the latest price summary for all tracked models, optionally filtered by brand.
    results = get_latest_summary(brand=brand)
    if not results:
        label = f"brand '{brand}'" if brand else "any model"
        raise HTTPException(status_code=404, detail=f"No price data found for {label}")
    return results


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn

    parser = argparse.ArgumentParser(description="Start the PricerBot API server")
    parser.add_argument("--host", default="127.0.0.1", help="Bind host (default: 127.0.0.1)")
    parser.add_argument("--port", type=int, default=8000, help="Bind port (default: 8000)")
    args = parser.parse_args()

    uvicorn.run("api:app", host=args.host, port=args.port, reload=False)
